# Generated by Django 5.1.3 on 2024-11-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='unit_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
